// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCGCollectionApp.Models;

namespace TCGCollectionApp.Migrations
{
    [DbContext(typeof(TCGCollectionContext))]
    [Migration("20191005000352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TCGCollectionApp.Models.MTGCard", b =>
                {
                    b.Property<string>("ID");

                    b.Property<bool>("IsFoil");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OracleID")
                        .IsRequired();

                    b.Property<string>("SetID")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("SetID");

                    b.ToTable("MTGCard");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGSet", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("MTGSet");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGCard", b =>
                {
                    b.HasOne("TCGCollectionApp.Models.MTGSet", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
