// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCGCollectionApp.Data;

namespace TCGCollectionApp.Migrations
{
    [DbContext(typeof(TCGCollectionContext))]
    partial class TCGCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TCGCollectionApp.Models.MTGCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArenaId")
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtistIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Booster")
                        .HasColumnType("bit");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardBackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cmc")
                        .HasColumnType("float");

                    b.Property<string>("CollectorNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorIdentityJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Digital")
                        .HasColumnType("bit");

                    b.Property<int>("EdhrecRank")
                        .HasColumnType("int");

                    b.Property<bool>("Foil")
                        .HasColumnType("bit");

                    b.Property<string>("Frame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FullArt")
                        .HasColumnType("bit");

                    b.Property<string>("GamesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HighresImage")
                        .HasColumnType("bit");

                    b.Property<string>("IllustrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageUrisId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegalitiesId")
                        .HasColumnType("int");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MtgoId")
                        .HasColumnType("int");

                    b.Property<string>("MultiverseIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Nonfoil")
                        .HasColumnType("bit");

                    b.Property<string>("Object")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OracleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oversized")
                        .HasColumnType("bit");

                    b.Property<int?>("PricesId")
                        .HasColumnType("int");

                    b.Property<string>("PrintsSearchUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Promo")
                        .HasColumnType("bit");

                    b.Property<int?>("PurchaseUrisId")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedUrisId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Reprint")
                        .HasColumnType("bit");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<string>("RulingsUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallSetUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetSearchUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StorySpotlight")
                        .HasColumnType("bit");

                    b.Property<int>("TcgplayerId")
                        .HasColumnType("int");

                    b.Property<bool>("Textless")
                        .HasColumnType("bit");

                    b.Property<string>("TypeLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Variation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ImageUrisId");

                    b.HasIndex("LegalitiesId");

                    b.HasIndex("PricesId");

                    b.HasIndex("PurchaseUrisId");

                    b.HasIndex("RelatedUrisId");

                    b.HasIndex("Set");

                    b.ToTable("MTGCard");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGCardFace", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IllustrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MTGCardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Object")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OracleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeLine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MTGCardId");

                    b.ToTable("MTGCardFace");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGImageUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtCrop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderCrop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Large")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Normal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Png")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Small")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MTGImageUris");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGLegalities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commander")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Future")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oldschool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pauper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pioneer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vintage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MTGLegalities");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGPrices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Eur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsdFoil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MTGPrices");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGPurchaseUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cardhoarder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cardmarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tcgplayer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MTGPurchaseUris");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGRelatedUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Edhrec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gatherer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mtgtop8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgplayerDecks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MTGRelatedUris");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGSet", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArenaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardCount")
                        .HasColumnType("int");

                    b.Property<bool>("Digital")
                        .HasColumnType("bit");

                    b.Property<bool>("FoilOnly")
                        .HasColumnType("bit");

                    b.Property<string>("IconSvgUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtgoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Object")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScryfallUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TcgplayerId")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("MTGSet");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGCard", b =>
                {
                    b.HasOne("TCGCollectionApp.Models.MTGImageUris", "ImageUris")
                        .WithMany()
                        .HasForeignKey("ImageUrisId");

                    b.HasOne("TCGCollectionApp.Models.MTGLegalities", "Legalities")
                        .WithMany()
                        .HasForeignKey("LegalitiesId");

                    b.HasOne("TCGCollectionApp.Models.MTGPrices", "Prices")
                        .WithMany()
                        .HasForeignKey("PricesId");

                    b.HasOne("TCGCollectionApp.Models.MTGPurchaseUris", "PurchaseUris")
                        .WithMany()
                        .HasForeignKey("PurchaseUrisId");

                    b.HasOne("TCGCollectionApp.Models.MTGRelatedUris", "RelatedUris")
                        .WithMany()
                        .HasForeignKey("RelatedUrisId");

                    b.HasOne("TCGCollectionApp.Models.MTGSet", null)
                        .WithMany("Cards")
                        .HasForeignKey("Set");
                });

            modelBuilder.Entity("TCGCollectionApp.Models.MTGCardFace", b =>
                {
                    b.HasOne("TCGCollectionApp.Models.MTGCard", null)
                        .WithMany("CardFaces")
                        .HasForeignKey("MTGCardId");
                });
#pragma warning restore 612, 618
        }
    }
}
